### ISSUE TITLE
Just a few quick questions.

### ISSUE THREAD

**Issue by CiaranKennedy** [sansomlab/tenx#91]
Hi there, really great work you guys are doing here, I'm new to analysing scRNAseq data and something like this looks like a really great starting point for what we're trying to do.

I just had a few quick questions. 
Firstly I'm just wondering what version(s) of seurat is the pipeline compatible with or is best to use with it? I'm using Seurat 3.1.1 at the moment for the pre-processing and running the script and have been able to do the full analysis on the individual datasets I'm using fine, but trying to run analysis on the integrated data including within-cluster DE analysis I keep getting an error in summarisemarkers while making the heatmaps, (I've attatched my summariseMarkers.log and pipeline.log) and I'm not sure where exactly the issue lies.
I was also wondering if it's possible to compare more than two conditions at once with the pipeline? At the moment we have 4 samples I'm looking to analyse, a control set + and - a growth factor and drug-treated cells +/- the same growth factor, what would be the proper way to set up findmarkers in the pipeline to be able to compare the response of the cells to the growth factor with and without the drug?

Thanks very much for the great work you have put into this pipeline!

[pipeline.log](https://github.com/sansomlab/tenx/files/4043035/pipeline.log)
[summariseMarkers.log](https://github.com/sansomlab/tenx/files/4043036/summariseMarkers.log)

**Comment by CiaranKennedy** [comment]
[summariseMarkers.log](https://github.com/sansomlab/tenx/files/4043031/summariseMarkers.log)
[pipeline.log](https://github.com/sansomlab/tenx/files/4043032/pipeline.log)

**Comment by snsansom** [comment]
Dear Ciaran,

Thanks for comments and interest. Currently we are running the pipelines with Seurat Version 3.1.1.

The issue that you are having with your integrated dataset is very likely due to the absence of a "scale.data" slot in the "RNA" assay. This is needed for some of the visualisations of gene expression levels, for which use of the "RNA" assay is recommended (as discussed here:  https://github.com/sansomlab/tenx/commit/d2e866d1c6e6ca23dcce9a481e6cbf79a1092773).

The "scale.data" slot can be added to the "RNA" assay very easily - for this please see our updated example here: https://github.com/sansomlab/tenx/blob/master/docs/AlignedExample.md.

Currently the pipeline only supports comparison of two conditions. For differential expression we generally recommend to adopt a pseudobulk approach which will allow more robust and flexible modelling of the data with packages such as EdgeR and DESeq2. See e.g. the muscat package (https://bioconductor.org/packages/devel/bioc/html/muscat.html).

Best wishes,
Steve
